Updated filters parameter handling

diff --git a/src/filters/map-sxml.in b/src/filters/map-sxml.in
--- a/src/filters/map-sxml.in
+++ b/src/filters/map-sxml.in
@@ -42,22 +42,24 @@ shift
 
 PARAMETERS="$*"
 
-echo "$me: Input:      $INPUT"
-echo "$me: Output:     $OUTPUT"
-echo "$me: Parameters: $PARAMETERS"
-
 if test X"$schemelibdir" != X"" ; then
     LIBDIR="$schemelibdir"
 else
     LIBDIR=@pkgvlibsdir@/scheme
 fi
 
+#echo "$me: Input:      $INPUT"
+#echo "$me: Output:     $OUTPUT"
+#echo "$me: Parameters: $PARAMETERS"
+#echo "$me: Libdir:     $LIBDIR"
+
 $GUILE $GUILE_FLAGS -l $LIBDIR/lib.scm $PARAMETERS -c '
 (map->sxml (open-input-file "'$INPUT'") (open-output-file "'$OUTPUT'"))
 (exit 0)
 ' || {
-	rm -f $OUTPUT ;
-	exit 1 ;
+    echo "$me: Error processing \`$INPUT'"
+    rm -f $OUTPUT
+    exit 1
 }
 
 exit 0
diff --git a/src/filters/news-wikitext.in b/src/filters/news-wikitext.in
--- a/src/filters/news-wikitext.in
+++ b/src/filters/news-wikitext.in
@@ -20,6 +20,27 @@
 # 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 #
 
-cp $1 $2 || exit 1
+me="news-wikitext"
+
+INPUT="$1"
+if test X"$INPUT" = X"" ; then
+    echo "$me: Missing input file"
+    exit 1
+fi
+
+OUTPUT="$2"
+if test X"$OUTPUT" = X"" ; then
+    echo "$me: Missing output file"
+    exit 1
+fi
+
+shift
+shift
+
+cp $INPUT $OUTPUT || {
+    echo "$me: Error processing \`$INPUT'"
+    rm -f $OUTPUT
+    exit 1
+}
 
 exit 0
